# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\code\getComics_py\View\Download.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Download(object):
    def setupUi(self, Download):
        Download.setObjectName("Download")
        Download.resize(859, 662)
        self.verticalLayout = QtWidgets.QVBoxLayout(Download)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(Download)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.comicComboBox = QtWidgets.QComboBox(Download)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comicComboBox.sizePolicy().hasHeightForWidth())
        self.comicComboBox.setSizePolicy(sizePolicy)
        self.comicComboBox.setObjectName("comicComboBox")
        self.comicComboBox.addItem("")
        self.horizontalLayout.addWidget(self.comicComboBox)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_3 = QtWidgets.QLabel(Download)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.chapterComboBox = QtWidgets.QComboBox(Download)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chapterComboBox.sizePolicy().hasHeightForWidth())
        self.chapterComboBox.setSizePolicy(sizePolicy)
        self.chapterComboBox.setObjectName("chapterComboBox")
        self.chapterComboBox.addItem("")
        self.horizontalLayout.addWidget(self.chapterComboBox)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.label = QtWidgets.QLabel(Download)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.statusComboBox = QtWidgets.QComboBox(Download)
        self.statusComboBox.setObjectName("statusComboBox")
        self.statusComboBox.addItem("")
        self.statusComboBox.addItem("")
        self.statusComboBox.addItem("")
        self.statusComboBox.addItem("")
        self.statusComboBox.addItem("")
        self.horizontalLayout.addWidget(self.statusComboBox)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.dwonloadButton = QtWidgets.QPushButton(Download)
        self.dwonloadButton.setObjectName("dwonloadButton")
        self.horizontalLayout.addWidget(self.dwonloadButton)
        self.pauseButton = QtWidgets.QPushButton(Download)
        self.pauseButton.setObjectName("pauseButton")
        self.horizontalLayout.addWidget(self.pauseButton)
        self.deleteButton = QtWidgets.QPushButton(Download)
        self.deleteButton.setObjectName("deleteButton")
        self.horizontalLayout.addWidget(self.deleteButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tableView = QtWidgets.QTableView(Download)
        self.tableView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableView.setObjectName("tableView")
        self.verticalLayout.addWidget(self.tableView)

        self.retranslateUi(Download)
        QtCore.QMetaObject.connectSlotsByName(Download)

    def retranslateUi(self, Download):
        _translate = QtCore.QCoreApplication.translate
        Download.setWindowTitle(_translate("Download", "Form"))
        self.label_2.setText(_translate("Download", "漫画"))
        self.comicComboBox.setItemText(0, _translate("Download", "全部"))
        self.label_3.setText(_translate("Download", "章节"))
        self.chapterComboBox.setItemText(0, _translate("Download", "全部"))
        self.label.setText(_translate("Download", "状态"))
        self.statusComboBox.setItemText(0, _translate("Download", "全部"))
        self.statusComboBox.setItemText(1, _translate("Download", "暂停"))
        self.statusComboBox.setItemText(2, _translate("Download", "下载中"))
        self.statusComboBox.setItemText(3, _translate("Download", "下载完成"))
        self.statusComboBox.setItemText(4, _translate("Download", "下载失败"))
        self.dwonloadButton.setText(_translate("Download", "下载"))
        self.pauseButton.setText(_translate("Download", "暂停"))
        self.deleteButton.setText(_translate("Download", "删除"))
