# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\code\getComics_py\View\Home.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Home(object):
    def setupUi(self, Home):
        Home.setObjectName("Home")
        Home.resize(459, 340)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(Home)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setContentsMargins(11, 11, 11, -1)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.comboBox = QtWidgets.QComboBox(Home)
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout_14.addWidget(self.comboBox)
        self.searchIcon = QtWidgets.QLabel(Home)
        self.searchIcon.setMinimumSize(QtCore.QSize(30, 30))
        self.searchIcon.setText("")
        self.searchIcon.setObjectName("searchIcon")
        self.horizontalLayout_14.addWidget(self.searchIcon)
        self.searchInput = QtWidgets.QLineEdit(Home)
        self.searchInput.setObjectName("searchInput")
        self.horizontalLayout_14.addWidget(self.searchInput)
        self.searchButton = QtWidgets.QPushButton(Home)
        self.searchButton.setObjectName("searchButton")
        self.horizontalLayout_14.addWidget(self.searchButton)
        self.verticalLayout_6.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.resultList = QtWidgets.QListView(Home)
        self.resultList.setMaximumSize(QtCore.QSize(300, 16777213))
        self.resultList.setResizeMode(QtWidgets.QListView.Adjust)
        self.resultList.setObjectName("resultList")
        self.horizontalLayout_15.addWidget(self.resultList)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        spacerItem = QtWidgets.QSpacerItem(227, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem)
        self.downloadButton = QtWidgets.QPushButton(Home)
        self.downloadButton.setObjectName("downloadButton")
        self.horizontalLayout_16.addWidget(self.downloadButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout_16)
        self.tableView = QtWidgets.QTableView(Home)
        self.tableView.setStyleSheet("")
        self.tableView.setAlternatingRowColors(True)
        self.tableView.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.tableView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableView.setGridStyle(QtCore.Qt.SolidLine)
        self.tableView.setObjectName("tableView")
        self.tableView.horizontalHeader().setVisible(False)
        self.tableView.verticalHeader().setVisible(False)
        self.verticalLayout_5.addWidget(self.tableView)
        self.horizontalLayout_15.addLayout(self.verticalLayout_5)
        self.verticalLayout_6.addLayout(self.horizontalLayout_15)

        self.retranslateUi(Home)
        QtCore.QMetaObject.connectSlotsByName(Home)

    def retranslateUi(self, Home):
        _translate = QtCore.QCoreApplication.translate
        Home.setWindowTitle(_translate("Home", "Form"))
        self.searchButton.setText(_translate("Home", "搜索"))
        self.downloadButton.setText(_translate("Home", "下载选中"))
